name: music_tools_flutter
description: A tool to edit tag of audio files, based on flutter.
publish_to: 'none'

version: 1.2.7

environment:
  sdk: '>=3.3.0-97.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  path: ^1.8.2
  path_provider: ^2.0.11
  transparent_image: ^2.0.0
  permission_handler: ^11.1.0
  file_picker: 8.1.4
  flutter_styled_toast: ^2.2.1
  cross_file: ^0.3.4+2
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0

flutter:
  uses-material-design: true
