name: music_tools_flutter
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-194.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7
  flutter_mobx: ^2.0.6
  path: ^1.8.2
  path_provider: ^2.0.11
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.1

flutter:
  uses-material-design: true
